/** Product-ranked free API registry for Chemistry Recipes. */

export type SourcePriority = "P0" | "P1" | "P2";

export interface ApiSource {
  id: string;
  name: string;
  organization: string;
  priority: SourcePriority;
  role: string;
  endpointUrl: string;
  docsUrl: string;
  category:
    | "identity"
    | "hazards"
    | "reactions"
    | "pathways"
    | "literature"
    | "patents"
    | "regulatory"
    | "supporting";
  notes?: string;
}

export const CHEMISTRY_API_SOURCES: ApiSource[] = [
  {
    id: "pubchem-pug",
    name: "PubChem PUG REST",
    organization: "NCBI (NIH)",
    priority: "P0",
    role: "Name/CAS/SMILES search, CID resolution, properties, structure images",
    endpointUrl: "https://pubchem.ncbi.nlm.nih.gov/rest/pug",
    docsUrl: "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
    category: "identity",
  },
  {
    id: "pubchem-pug-view",
    name: "PubChem PUG View",
    organization: "NCBI (NIH)",
    priority: "P0",
    role: "Sectioned records: GHS hazards, use & manufacturing text",
    endpointUrl: "https://pubchem.ncbi.nlm.nih.gov/rest/pug_view",
    docsUrl: "https://pubchem.ncbi.nlm.nih.gov/docs/pug-view",
    category: "hazards",
  },
  {
    id: "unichem",
    name: "UniChem",
    organization: "EMBL-EBI",
    priority: "P0",
    role: "Cross-database chemical identifier mapping",
    endpointUrl: "https://www.ebi.ac.uk/unichem/rest",
    docsUrl: "https://www.ebi.ac.uk/unichem/info/wsoverview",
    category: "identity",
  },
  {
    id: "chebi",
    name: "ChEBI",
    organization: "EMBL-EBI",
    priority: "P0",
    role: "Chemical ontology and biological roles",
    endpointUrl: "https://www.ebi.ac.uk/chebi/api/data",
    docsUrl: "https://www.ebi.ac.uk/chebi/about",
    category: "identity",
  },
  {
    id: "mychem",
    name: "MyChem.info",
    organization: "BioThings",
    priority: "P0",
    role: "Aggregated chemical annotation",
    endpointUrl: "https://mychem.info/v1",
    docsUrl: "https://mychem.info/v1",
    category: "identity",
  },
  {
    id: "gsrs",
    name: "GSRS / UNII",
    organization: "FDA",
    priority: "P0",
    role: "Global substance registration identifiers",
    endpointUrl: "https://gsrs.ncats.nih.gov/api",
    docsUrl: "https://gsrs.ncats.nih.gov/api",
    category: "identity",
  },
  {
    id: "comptox",
    name: "EPA CompTox",
    organization: "EPA",
    priority: "P0",
    role: "DTXSID, toxicology and exposure context",
    endpointUrl: "https://comptox.epa.gov/dashboard-api",
    docsUrl: "https://www.epa.gov/comptox-tools",
    category: "hazards",
  },
  {
    id: "kegg",
    name: "KEGG REST",
    organization: "KEGG / Kyoto University",
    priority: "P1",
    role: "Compound–reaction–pathway (often biosynthetic)",
    endpointUrl: "https://rest.kegg.jp",
    docsUrl: "https://www.kegg.jp/kegg/rest/keggapi.html",
    category: "pathways",
    notes: "Not a substitute for industrial organic routes.",
  },
  {
    id: "rhea",
    name: "Rhea",
    organization: "SIB / EMBL-EBI",
    priority: "P1",
    role: "Expert-curated enzyme-catalyzed reactions (biocatalytic context)",
    endpointUrl: "https://www.rhea-db.org/rhea",
    docsUrl: "https://www.rhea-db.org/help/rest-api",
    category: "reactions",
    notes:
      "Wired into live gather. Not a substitute for industrial organic routes.",
  },
  {
    id: "reactome",
    name: "Reactome",
    organization: "Reactome",
    priority: "P1",
    role: "Curated biological pathway maps",
    endpointUrl: "https://reactome.org/ContentService",
    docsUrl: "https://reactome.org/dev/content-service",
    category: "pathways",
  },
  {
    id: "wikipathways",
    name: "WikiPathways",
    organization: "WikiPathways",
    priority: "P1",
    role: "Community pathway models (via free Pathway Commons when legacy WS is down)",
    endpointUrl: "https://www.pathwaycommons.org/pc2",
    docsUrl: "https://www.wikipathways.org/",
    category: "pathways",
    notes:
      "Legacy webservice.wikipathways.org retired; live gather uses Pathway Commons PC2 + WP site deep links.",
  },
  {
    id: "pathway-commons",
    name: "Pathway Commons",
    organization: "UBC / EMBL-EBI",
    priority: "P1",
    role: "Integrated pathway interaction graphs",
    endpointUrl: "https://www.pathwaycommons.org/pc2",
    docsUrl: "https://www.pathwaycommons.org/pc2/",
    category: "pathways",
  },
  {
    id: "ord",
    name: "Open Reaction Database",
    organization: "ORD community",
    priority: "P1",
    role: "Structured organic reaction records (browse + best-effort snippets + bulk datasets)",
    endpointUrl: "https://open-reaction-database.org/",
    docsUrl: "https://docs.open-reaction-database.org/",
    category: "reactions",
    notes:
      "Live gather deep-links browse and attempts HTML snippets for process facts. Prefer bulk download for ML/offline ingest; not plant SOPs.",
  },
  {
    id: "europepmc-oa",
    name: "Europe PMC OA full text",
    organization: "EMBL-EBI",
    priority: "P1",
    role: "Open-access fullTextXML → experimental/methods windows for process facts",
    endpointUrl: "https://www.ebi.ac.uk/europepmc/webservices/rest",
    docsUrl: "https://europepmc.org/RestfulWebService",
    category: "literature",
    notes: "Densifies recipe readiness when OA PMC full text exists.",
  },
  {
    id: "europepmc-patents",
    name: "Europe PMC patents (SRC:PAT)",
    organization: "EMBL-EBI",
    priority: "P1",
    role: "Patent literature abstracts for process / preparation densification",
    endpointUrl: "https://www.ebi.ac.uk/europepmc/webservices/rest",
    docsUrl: "https://europepmc.org/RestfulWebService",
    category: "patents",
  },
  {
    id: "pubchem-patents",
    name: "PubChem Patent xrefs",
    organization: "NCBI (NIH)",
    priority: "P1",
    role: "Patent IDs linked to a CID (free; complements PatentsView)",
    endpointUrl: "https://pubchem.ncbi.nlm.nih.gov/rest/pug",
    docsUrl: "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
    category: "patents",
  },
  {
    id: "patentsview",
    name: "PatentsView / free patent densify",
    organization: "USPTO / PatentsView / Europe PMC",
    priority: "P1",
    role: "Process patents (PatentsView when online+key; free Europe PMC SRC:PAT + PubChem PUG View densify always)",
    endpointUrl: "https://www.ebi.ac.uk/europepmc/webservices/rest",
    docsUrl: "https://data.uspto.gov/support/transition-guide/patentsview",
    category: "patents",
    notes:
      "PatentsView PatentSearch host is migrating to USPTO Open Data Portal (2026). Live gather free-falls to Europe PMC patents.",
  },
  {
    id: "europepmc",
    name: "Europe PMC",
    organization: "EMBL-EBI",
    priority: "P1",
    role: "Process chemistry and organic synthesis literature",
    endpointUrl: "https://www.ebi.ac.uk/europepmc/webservices/rest",
    docsUrl: "https://europepmc.org/RestfulWebService",
    category: "literature",
  },
  {
    id: "pubmed",
    name: "PubMed E-utilities",
    organization: "NLM (NIH)",
    priority: "P1",
    role: "Biomedical and chemical literature search",
    endpointUrl: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
    docsUrl: "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
    category: "literature",
  },
  {
    id: "openalex",
    name: "OpenAlex",
    organization: "OurResearch",
    priority: "P1",
    role: "Scholarly works graph and concepts",
    endpointUrl: "https://api.openalex.org",
    docsUrl: "https://docs.openalex.org/",
    category: "literature",
  },
  {
    id: "crossref",
    name: "CrossRef",
    organization: "CrossRef",
    priority: "P1",
    role: "DOI metadata and citation links",
    endpointUrl: "https://api.crossref.org/works",
    docsUrl: "https://api.crossref.org/",
    category: "literature",
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    organization: "AI2",
    priority: "P1",
    role: "Related papers and influence metrics (rate-limited free tier)",
    endpointUrl: "https://api.semanticscholar.org/graph/v1",
    docsUrl: "https://api.semanticscholar.org/",
    category: "literature",
    notes:
      "Optional free key SEMANTIC_SCHOLAR_API_KEY / S2_API_KEY raises rate limits. Soft-fails on 429.",
  },
  {
    id: "openfda",
    name: "openFDA",
    organization: "U.S. FDA",
    priority: "P1",
    role: "Drug labels, Drugs@FDA, NDC (live dossier regulatory annotations)",
    endpointUrl: "https://api.fda.gov",
    docsUrl: "https://open.fda.gov/api/",
    category: "regulatory",
  },
  {
    id: "rxnorm",
    name: "RxNorm",
    organization: "NLM (NIH)",
    priority: "P1",
    role: "Drug name normalization (RxCUI) for live dossier identity",
    endpointUrl: "https://rxnav.nlm.nih.gov/REST",
    docsUrl: "https://lhncbc.nlm.nih.gov/RxNav/APIs/RxNormAPIs.html",
    category: "identity",
  },
  {
    id: "dailymed",
    name: "DailyMed",
    organization: "NLM (NIH)",
    priority: "P2",
    role: "FDA labeling (formulation context, not synthesis)",
    endpointUrl: "https://dailymed.nlm.nih.gov/dailymed/services/v2",
    docsUrl: "https://dailymed.nlm.nih.gov/dailymed/app-support.cfm#api",
    category: "regulatory",
  },
  {
    id: "chembl",
    name: "ChEMBL",
    organization: "EMBL-EBI",
    priority: "P0",
    role: "Molecule identity, clinical max phase, and mechanisms (live dossier)",
    endpointUrl: "https://www.ebi.ac.uk/chembl/api/data",
    docsUrl: "https://www.ebi.ac.uk/chembl/",
    category: "identity",
  },
  {
    id: "massbank",
    name: "MassBank",
    organization: "MassBank",
    priority: "P2",
    role: "MS reference spectra (REST API retired — site search only; no harvest)",
    endpointUrl: "https://massbank.eu/MassBank-api/records",
    docsUrl: "https://massbank.eu/MassBank-api",
    category: "supporting",
  },
  {
    id: "arxiv",
    name: "arXiv",
    organization: "Cornell University",
    priority: "P1",
    role: "Process / catalysis preprints (free full abstracts; OA)",
    endpointUrl: "https://export.arxiv.org/api/query",
    docsUrl: "https://info.arxiv.org/help/api/user-manual.html",
    category: "literature",
    notes: "Wired into live gather for process-chem densification.",
  },
  {
    id: "orgsyn",
    name: "Organic Syntheses",
    organization: "Organic Syntheses, Inc.",
    priority: "P1",
    role: "Classic validated prep procedures (HTML extract; educational)",
    endpointUrl: "https://www.orgsyn.org/",
    docsUrl: "https://www.orgsyn.org/",
    category: "literature",
    notes: "No bulk API — live gather searches + extracts procedure HTML when matched.",
  },
  {
    id: "uspto-pubchem-patent",
    name: "PubChem patent records",
    organization: "NCBI (NIH)",
    priority: "P1",
    role: "Patent abstract densification for US IDs (complements PatentsView)",
    endpointUrl: "https://pubchem.ncbi.nlm.nih.gov/rest/pug/patent",
    docsUrl: "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
    category: "patents",
  },
  {
    id: "drugcentral",
    name: "DrugCentral",
    organization: "UNM / DrugCentral",
    priority: "P2",
    role: "Drug card identity / structure links (wired live gather)",
    endpointUrl: "https://drugcentral.org/api/v1",
    docsUrl: "https://drugcentral.org/",
    category: "identity",
  },
  {
    id: "clinicaltrials",
    name: "ClinicalTrials.gov",
    organization: "NLM (NIH)",
    priority: "P2",
    role: "Study metadata for clinical scale / formulation context (not synthesis)",
    endpointUrl: "https://clinicaltrials.gov/api/v2",
    docsUrl: "https://clinicaltrials.gov/data-api/about-api",
    category: "regulatory",
  },
  {
    id: "pubchem-classification",
    name: "PubChem Classification / MeSH",
    organization: "NCBI (NIH)",
    priority: "P1",
    role: "PharmAction / MeSH / PubMed xrefs for denser identity",
    endpointUrl: "https://pubchem.ncbi.nlm.nih.gov/rest/pug",
    docsUrl: "https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest",
    category: "identity",
  },
];

export function sourcesByPriority(priority?: SourcePriority): ApiSource[] {
  if (!priority) return CHEMISTRY_API_SOURCES;
  return CHEMISTRY_API_SOURCES.filter((s) => s.priority === priority);
}
