/**
 * Short site handoff pack — email/print body from free-public facts only.
 * Not a batch record; not GMP.
 */

import type { LiveDossier } from "@/lib/dossier/types";
import { honestSiteHandoffProcessFacts } from "@/lib/dossier/sectionHonesty";

export function buildSiteHandoffMarkdown(d: LiveDossier): string {
  const name = d.identity?.name || `CID ${d.cid}`;
  const lines: string[] = [];
  lines.push(`# Site handoff · ${name} (CID ${d.cid})`);
  lines.push("");
  lines.push(
    "> **Not GMP.** Free-public densify scaffold only. Validate under site QMS."
  );
  lines.push("");
  lines.push("## Snapshot");
  lines.push(
    `- Ideal depth: **${d.idealParity?.score ?? "—"}**/100 · Evidence: **${d.evidenceScore?.score ?? "—"}**/100`
  );
  lines.push(
    `- ${honestSiteHandoffProcessFacts({
      factCount:
        d.processFacts?.facts?.filter((f) => f.kind !== "open-gap").length ?? 0,
      traces: d.traces,
      fetchErrors: d.fetchErrors,
    }).value} · Framing: ${d.processFraming || d.processFacts?.framing || "—"}`
  );
  lines.push(
    `- Soft-fail notes: **${(d.fetchErrors || []).filter((e: string) => e.startsWith("soft-fail ·") || e.startsWith("api-fail ·")).length}**`
  );
  lines.push("");

  const mfg =
    d.synthesis?.manufacturingSummary ||
    d.manufacturingTexts?.[0] ||
    "";
  if (mfg) {
    lines.push("## Manufacturing summary (public)");
    lines.push(mfg.slice(0, 1200));
    lines.push("");
  }

  const facts = (d.processFacts?.facts || [])
    .filter((f) => f.kind === "condition" || f.kind === "yield")
    .slice(0, 12);
  if (facts.length) {
    lines.push("## Sourced conditions (quote-bound)");
    for (const f of facts) {
      lines.push(
        `- **${f.claim}**${f.value ? ` · ${f.value}${f.unit ? " " + f.unit : ""}` : ""}${f.quote ? ` — “${f.quote.slice(0, 120)}”` : ""}`
      );
    }
    lines.push("");
  }

  const gaps = d.processFacts?.openGaps?.slice(0, 8) || [];
  if (gaps.length) {
    lines.push("## Open gaps (public evidence)");
    for (const g of gaps) lines.push(`- ${g}`);
    lines.push("");
  }

  const conflicts = d.processKnowledge?.conflicts?.slice(0, 5) || [];
  if (conflicts.length) {
    lines.push("## Scientific conflicts (research)");
    for (const c of conflicts) {
      lines.push(`### ${c.topic}`);
      lines.push(`- A: ${c.sideA.slice(0, 160)}`);
      lines.push(`- B: ${c.sideB.slice(0, 160)}`);
      if (c.resolvingExperiment) {
        lines.push(`- Resolve: ${c.resolvingExperiment}`);
      }
    }
    lines.push("");
  }

  lines.push("## Provenance");
  lines.push(
    `- Live HTTP captures: ${d.traces?.length ?? 0} · Source refs: ${d.sourceRefs?.length ?? 0}`
  );
  lines.push(
    `- PubChem: https://pubchem.ncbi.nlm.nih.gov/compound/${d.cid}`
  );
  lines.push("");
  lines.push("---");
  lines.push(
    "Generated by Chemistry Recipes · free-public densify · not a clinical or batch record."
  );
  return lines.join("\n");
}

export function downloadSiteHandoff(d: LiveDossier): void {
  const md = buildSiteHandoffMarkdown(d);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `site-handoff-cid-${d.cid}.md`;
  a.click();
  URL.revokeObjectURL(a.href);
}
